version: '3.8'

services:

  web_hoffmann:
    build: ./web
    container_name: web_hoffmann
    ports:
      - "4321:4321"
    networks:
      - bridge
    dns:
      - "8.8.8.8"

networks:
  bridge:
    external: true